### ISSUE TITLE
Facing issue when middleware authentication enabled

### ISSUE THREAD

**Issue by navjotdhanawat** [SocketCluster/sc-stateless-presence#1]
I had first authenticated user using 'login' channel
Then registered groups using setAuthToken to get publish permission over a particular channel.

I had also include presence channel id while setting token as below:
var presenceChannel = 'presence>socket/' + socket.id;

But getting 
You are not authorized to publish to  presence>socket/gmodlUB2u8HTqS4oAAAF.

**Comment by jondubois** [comment]
@navjotdhanawat If you've added custom middleware functions on your SC instance, you need to make sure that your middleware allows all channels which start with `presence>`.

**Comment by navjotdhanawat** [comment]
@jondubois Exactly same I had done.
Thank You!!!
