### ISSUE TITLE
Uncaught ReferenceError: socket is not defined

### ISSUE THREAD

**Issue by texag93** [SocketCluster/sc-stateless-presence#3]
https://github.com/SocketCluster/sc-stateless-presence/blob/caecfd23f9d0a000d4712dc0aaaf3cb749a81a55/sc-stateless-presence-client.js#L175

The socket is stored on self. This fixes the problem:
self._sendSocketChannelPong(self.socket, channelName, presencePacket);

**Comment by jondubois** [comment]
@texag93 Thanks, fixed in v1.0.5.
